version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: IPDB
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data:z
